name: Test Deployment
on:
  deployment_status:

permissions: read-all

jobs:
  e2eTests:
    if:
      github.repository == 'FahradLevonyan/github-readme-stats' &&
      github.event_name == 'deployment_status' &&
      github.event.deployment_status.state == 'success'
    name: Perform 2e2 tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: Setup Node
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: Run end-to-end tests.
        run: npm run test:e2e
        env:
          VERCEL_PREVIEW_URL: ${{ github.event.deployment_status.target_url }}
